services:
  app: 
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo_tmpfs:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    tmpfs:
      - /data/db